name: Generate Snake

on:
  schedule:
    # Runs at 6:00 AM UTC daily
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Generate the snake
      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: MashiAma
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Push the generated snake to the repository
      - name: Push Snake
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@users.noreply.github.com"
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Generated snake"
          git push
